### ISSUE TITLE
Privacy concern, Users email address's being shown :(

### ISSUE THREAD

**Issue by siliconart** [forumthemer/eles-phpbb-forum-theme#33] opened 2017-07-27 12:19 UTC
When viewing a User Profile, there is the option to “Send an email to User. I cant seem to find a way to turn that function off, as it causes the Users email address to be shown to everyone.

I feel this is a Privacy issue.

**Comment by forumthemer** [comment] 2017-07-31 19:47
test

**Comment by Leinad4Mind** [comment] 2017-08-04 23:54
You can disable it on ACP. General tab. Client communication - E-mail settings.

**Comment by siliconart** [comment] 2017-08-05 06:08
Umm, well I seem to have 2 options there:

1. Disable all email functionality- But then this stops the email verification / Registration process.
2. Hide email addresses- I have this option turned on, but can still see User email addresses.

:(

**Comment by Leinad4Mind** [comment] 2017-08-05 11:22
It's the 2nd option. I didn't check myself with the theme but If it doesn't work then it's a bug of the theme. It misses a variable on that memberlist page.

**Comment by thekendog** [comment] 2017-08-22 20:47
Yup, I can confirm the same thing is happening for me.  In general, this seems like a very poor update.

**Comment by forumthemer** [comment] 2018-01-23 10:08
Guys, could you please explain the issue a little bit more in detail.

I checked the code but it seems to be the same as prosilver on that page.

Is this "issue" also on prosilver?

Cheers

**Comment by forumthemer** [comment] 2018-01-23 10:17
Checked the issue in detail, I don't think it is a bug. You can only see the "Send an email to User" because you are and admin.

I tested it with admin/normal user.

I'm closing this one as an Invalid bug

**Closed as completed by forumthemer** 2018-01-23 10:17 UTC
Labels: invalid
